#################################
# General setup
#################################
language: python

sudo: false

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################

before_install:
  - echo "-----before_install-----"


install:
  - echo "-----install-----"
  # Make sure I'm in the correct directory after all that before_install crap

script:
  - echo "-----script-----"
#  - nosetests
  - python --version

#################################
# Additional Items
#################################
#addons:
#  apt:
#    packages:
#      - libghc-gstreamer-dev
#      - dpkg-dev
#      - libnotify
#      - libsdl1.2-dev
#
#      # For wxPython?
#      - dpkg-dev
#      - build-essential
#      - python3.4-dev
#      - libwebkitgtk-dev
#      - libjpeg-dev
#      - libtiff-dev
#      - libgtk2.0-dev
#      - libsdl1.2-dev
#      - libgstreamer-plugins-base0.10-dev
#      - freeglut3
#      - freeglut3-dev
