language: python

python:
  - "2.7"

notifications:
  email: False

# command to install dependencies
before_install:
  #- "sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n libwxgtk2.8-dev libgtk2.0-dev"
- sudo apt-get install python-wxgtk2.8
- wget "http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1820+49a8884-cp27-none-win32.whl"

install:
  - pip install --upgrade
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install wheel
  - pip install "wxPython_Phoenix-3.0.3.dev1820+49a8884-cp27-none-win32.whl"

# command to run tests
script:
  #- nosetests
  - python --version